### ISSUE TITLE
Hotkey support

### ISSUE THREAD

**Issue by ds6** [ds6/pru#7]
Add hotkey support, possibly customizable keys.
Examples:
Ctrl+Alt+R to open a reservation page from reservation ID on clipboard
Ctrl+Alt+N to open an input box to create a notation with
Ctrl+Alt+T to calculate the elapsed time between the exam start and now

**Comment by LifeReaper** [comment]
Can you clarify Ctrl+Alt+N? does the textbox place the not on the page?

**Comment by ds6** [comment]
prompt() would be easiest

**Comment by ds6** [comment]
implimented as alt+q, alt+w, alt+s, alt+r
